# Generated by Django 2.2.6 on 2020-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
