# Generated by Django 2.2.6 on 2020-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='company',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='company',
            field=models.CharField(max_length=128),
        ),
    ]
